### ISSUE TITLE
Feature: Helm / Terraform SetVariables functionality

### ISSUE THREAD

**Issue by DenisBiondic** [conplementAG/cops-hq#15]
Code brainstorming:

/*

var variables = make(map[string]interface{})

merge(variables, viper.Get("application"))

variables["env_tag"] = viper.Get("env-tag")
variables["subscription_id"] = viper.Get("subscription_id")

x.SetVariables(variables)

*/

func BuildVariables() {
	var variables = make(map[string]interface{}) 
	
	applicationConfig := viper.GetStringMap("application")
	variables["subscription_id"] = viper.GetString("subscription_id")
	
	SetVariables(variables) 
}

**Comment by huf1** [comment]
feature added with version 0.6.0
